"""add subtitles field to MediaItem

Revision ID: 376a10cf5f74
Revises: df92b0998b20
Create Date: 2026-01-30 21:09:40.225884

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "376a10cf5f74"
down_revision: Union[str, Sequence[str], None] = "df92b0998b20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("media_items", sa.Column("subtitles", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media_items", "subtitles")
    # ### end Alembic commands ###
