"""add saga_file_move_log table

Revision ID: 8f469dd7ba3c
Revises: 376a10cf5f74
Create Date: 2026-01-31 13:08:52.917766

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f469dd7ba3c"
down_revision: Union[str, Sequence[str], None] = "376a10cf5f74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "media_items", sa.Column("audio_fingerprint", sa.String(), nullable=True)
    )
    op.add_column(
        "media_items", sa.Column("video_fingerprint", sa.String(), nullable=True)
    )
    op.create_index(
        op.f("ix_media_items_audio_fingerprint"),
        "media_items",
        ["audio_fingerprint"],
        unique=False,
    )
    op.create_index(
        op.f("ix_media_items_video_fingerprint"),
        "media_items",
        ["video_fingerprint"],
        unique=False,
    )
    op.add_column(
        "normalization_plans", sa.Column("needs_tagging", sa.Boolean(), nullable=False)
    )
    op.create_table(
        "saga_file_move_log",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("plan_id", sa.String(), nullable=False),
        sa.Column("src_path", sa.String(), nullable=False),
        sa.Column("tmp_path", sa.String(), nullable=False),
        sa.Column("dest_path", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("prepared", "committed", "cleaned", "failed", name="sagalogstatus"),
            nullable=False,
            server_default="prepared",
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            onupdate=sa.func.now(),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("saga_file_move_log")
    op.drop_column("normalization_plans", "needs_tagging")
    op.drop_index(op.f("ix_media_items_video_fingerprint"), table_name="media_items")
    op.drop_index(op.f("ix_media_items_audio_fingerprint"), table_name="media_items")
    op.drop_column("media_items", "video_fingerprint")
    op.drop_column("media_items", "audio_fingerprint")
    # ### end Alembic commands ###
