"""add guessed_title and guessed_year to MediaItem

Revision ID: df92b0998b20
Revises:
Create Date: 2026-01-30 20:42:15.279781

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df92b0998b20"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("source_path", sa.String(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "pending",
                "scanning",
                "scanned",
                "enriched",
                "planned",
                "executed",
                "validated",
                "audited",
                "error",
                name="filestate",
            ),
            nullable=False,
        ),
        sa.Column(
            "media_type",
            sa.Enum("movie", "series", "music", "unknown", name="mediatype"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("container", sa.String(), nullable=True),
        sa.Column("video_codec", sa.String(), nullable=True),
        sa.Column("video_width", sa.Integer(), nullable=True),
        sa.Column("video_height", sa.Integer(), nullable=True),
        sa.Column("video_bitrate", sa.Integer(), nullable=True),
        sa.Column("canonical_title", sa.String(), nullable=True),
        sa.Column("release_year", sa.Integer(), nullable=True),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("poster_path", sa.String(), nullable=True),
        sa.Column("enrichment_failed", sa.Boolean(), nullable=True),
        sa.Column("guessed_title", sa.String(), nullable=True),
        sa.Column("guessed_year", sa.Integer(), nullable=True),
        sa.Column("album_artist", sa.String(), nullable=True),
        sa.Column("album_name", sa.String(), nullable=True),
        sa.Column("disc_number", sa.Integer(), nullable=True),
        sa.Column("mbid", sa.String(), nullable=True),
        sa.Column("release_mbid", sa.String(), nullable=True),
        sa.Column("canonical_series_name", sa.String(), nullable=True),
        sa.Column("episode_title", sa.String(), nullable=True),
        sa.Column("absolute_number", sa.Integer(), nullable=True),
        sa.Column("overview", sa.String(), nullable=True),
        sa.Column("tmdb_series_id", sa.Integer(), nullable=True),
        sa.Column("metadata_mismatch", sa.Boolean(), nullable=True),
        sa.Column("video_fps", sa.String(), nullable=True),
        sa.Column("audio_codec", sa.String(), nullable=True),
        sa.Column("audio_channels", sa.String(), nullable=True),
        sa.Column("audio_language", sa.String(), nullable=True),
        sa.Column("has_subtitles", sa.Boolean(), nullable=True),
        sa.Column("subtitle_format", sa.String(), nullable=True),
        sa.Column("subtitle_language", sa.String(), nullable=True),
        sa.Column("artist", sa.String(), nullable=True),
        sa.Column("album", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("year", sa.String(), nullable=True),
        sa.Column("is_standard_compliant", sa.Boolean(), nullable=True),
        sa.Column("error_log", sa.Text(), nullable=True),
        sa.Column("enrichment_data", sa.Text(), nullable=True),
        sa.Column("detected_issues", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_path"),
    )
    op.create_table(
        "normalization_plans",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("media_item_id", sa.String(), nullable=False),
        sa.Column("needs_transcode", sa.Boolean(), nullable=False),
        sa.Column("needs_rename", sa.Boolean(), nullable=False),
        sa.Column("needs_subtitle_conversion", sa.Boolean(), nullable=False),
        sa.Column("target_path", sa.String(), nullable=False),
        sa.Column("ffmpeg_args", sa.JSON(), nullable=True),
        sa.Column("original_hash", sa.String(), nullable=False),
        sa.Column(
            "plan_status",
            sa.Enum(
                "draft",
                "approved",
                "executing",
                "completed",
                "failed",
                name="planstatus",
            ),
            nullable=False,
        ),
        sa.Column("execution_log", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["media_item_id"],
            ["media_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("media_item_id"),
        sa.UniqueConstraint("target_path", name="uq_normalizationplan_target_path"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("normalization_plans")
    op.drop_table("media_items")
    # ### end Alembic commands ###
