"""add size column to MediaItem

Revision ID: f27e40bf3f18
Revises: 9f1e2a
Create Date: 2026-01-31 17:43:56.672955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f27e40bf3f18"
down_revision: Union[str, Sequence[str], None] = "9f1e2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("saga_file_move_log")
    op.add_column("media_items", sa.Column("size", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media_items", "size")
    op.create_table(
        "saga_file_move_log",
        sa.Column("id", sa.VARCHAR(), nullable=False),
        sa.Column("plan_id", sa.VARCHAR(), nullable=False),
        sa.Column("src_path", sa.VARCHAR(), nullable=False),
        sa.Column("tmp_path", sa.VARCHAR(), nullable=False),
        sa.Column("dest_path", sa.VARCHAR(), nullable=False),
        sa.Column(
            "status",
            sa.VARCHAR(length=9),
            server_default=sa.text("'prepared'"),
            nullable=False,
        ),
        sa.Column("error", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
